config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'about#index'

  get 'home/index'

  resources :authors, only: [:index, :show]
  resources :books, only: [:index, :show]

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books

  validates :name, presence: true, uniqueness: true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :identifiers
  has_one :cover
  has_and_belongs_to_many :authors

  validates :title, presence: true
  validates :publishDate, length: { minimum: 4 }, allow_blank: true
end

app/models/cover.rb
class Cover < ApplicationRecord
  belongs_to :book

  # Regex from stack overflow: https://stackoverflow.com/questions/34561083/how-to-validate-url-in-rails-model
  URL_REGEX = /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/ix
  validates :smallLink, :mediumLink, :largeLink, presence: true, format: { with: URL_REGEX, message: 'not a URL'}
end

app/models/identifier.rb
class Identifier < ApplicationRecord
  belongs_to :book

  validates :idType, :number, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :authors, :numberOfPages, :cover)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Books</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr data-link="<%= author_path(author) %>">
        <td><%= author.name %></td>
        <td><%= author.books.size %></td>
        <td><%= link_to 'Show', author %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<ul>
  <% @author.books.each do |book| %>
    <li><%= link_to book.title, book_path(book)%></li>
  <% end %>
</ul>

<%= link_to 'Back', authors_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Cover</th>
      <th>Title</th>
      <th>Authors</th>
      <th>Numberofpages</th>
      <th>Publish Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr data-link="<%= book_path(book) %>">
        <td><%= image_tag book.cover.smallLink %></td>
        <td><%= book.title %></td>
        <td><%= book.authors.map { |a| a.name } * ", " %></td>
        <td><%= book.numberOfPages %></td>
        <td><%= book.publishDate %></td>
        <td><%= link_to 'Show', book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @book.title %></h1>

<p>
  <strong>Cover:</strong>
  <div>
    <%= image_tag @book.cover.largeLink %>
  </div>
</p>

<p>
  <strong>Authors:</strong>
  <ul>
      <% @book.authors.each do |author| %>
        <li><%= link_to author.name, author_path(author)%></li>
      <% end %>
  </ul>
</p>

<p>
  <strong>Identifiers</strong>
  <ul>
    <% @book.identifiers.each do |ids| %>
      <li><strong><%= ids.idType %>:</strong> <%= ids.number %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Number of pages:</strong>
  <%= @book.numberOfPages %>
</p>

<p>
  <strong>Publish Date</strong>
  <%= @book.publishDate %>
</p>

<%= link_to 'Back', books_path %>

app/views/home/index.html.erb
<h1>Welcome to Daniel's Intro to Rails Project!</h1>
<p><%= link_to 'Browse books', books_path %></p>
<p><%= link_to 'Browse authors', authors_path %></p>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'About', about_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenLibraryProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header><%= render 'layouts/navigation' %></header>
    <%= yield %>
  </body>
</html>